Repository dream11/lua-circuit-breaker, pull requests merged in 2021-06, with the labels that each got.

#6 docs: add config theme to github pages
  docs/_config.yml
Labels: maintenance

#7 test: add code coverage
  .ci/scripts/install-deps.sh
  .github/workflows/ci.yml
  .luacov
  README.md
  config.lua
  lua-circuit-breaker-1.0.0-1.rockspec
  luacov.report.out
  src/breaker.lua
  src/counters.lua
  src/errors.lua
  src/factory.lua
  src/oop.lua
  src/utils.lua
Labels: ci, lua-code-changed, maintenance

#8 ci: add code coverage badge
  .github/workflows/ci.yml
  README.md
  docs/index.md
Labels: ci, maintenance

#9 chore: gitignore luacov.report
  .gitignore
  luacov.report.out
Labels: maintenance

#10 fix: import statement in modules
  src/counters.lua
  src/factory.lua
Labels: fix, lua-code-changed

#13 docs: update readme & docs/index
  README.md
  docs/index.md
Labels: maintenance

#12 chore: fix logs and update readme
  README.md
  docs/index.md
  src/breaker.lua
  src/factory.lua
  src/utils.lua
  test/test.lua
Labels: fix, lua-code-changed, maintenance

#14 chore: increase code coverage and update docs
  .gitignore
  README.md
  docs/index.md
  src/factory.lua
  test/test.lua
Labels: lua-code-changed, maintenance

#16 ci: release automation scripts
  .ci/scripts/bump-rockspec.sh
  .ci/scripts/upload.sh
  .github/release-drafter.yml
  .github/workflows/draft-and-bump.yml
  .github/workflows/pr-labeler.yml
  .github/workflows/release.yml
Labels: ci, enhancement, maintenance

#17 docs: improve how does it work section in readme
  README.md
  docs/index.md
Labels: maintenance
